### PR TITLE
pages: don't render input list until blueprint is loaded

### LINKED ISSUE #1005: check-package.TestPackage.testDiscard is flaky
The `check-package.TestPackage.testDiscard` test sometimes fails in RHEL gating. I couldn't reproduce this locally yet.

```
# 1 TEST FAILED [59s on ibm-p8-kvm-03-guest-02]
Started /usr/lib64/chromium-browser/headless_shell (pid 63546) on port 10103
Traceback (most recent call last):
  File "test/verify/check-package", line 219, in testDiscard
    b.click("li[data-input=cockpit-composer] .fa-plus")
  File "/var/str/source/test/common/testlib.py", line 215, in click
    self.mouse(selector + ":not([disabled])", "click", 0, 0, 0)
  File "/var/str/source/test/common/testlib.py", line 212, in mouse
    self.call_js_func('ph_mouse', selector, type, x, y, btn, ctrlKey, shiftKey, altKey, metaKey)
  File "/var/str/source/test/common/testlib.py", line 196, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/var/str/source/test/common/testlib.py", line 180, in eval_js
    silent=False, awaitPromise=True, returnByValue=True, no_trace=no_trace)
  File "/var/str/source/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/var/str/source/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: Cannot read property 'concat' of undefined
```

### PR DESCRIPTION
**Pull request by jkozol**
The input list allows users to add and remove components from a blueprint. These actions can not occur if the blueprint is still being fetched. By disabling the input list until the blueprint is loaded the
user is prevented from interacting with the list when it may reflect inaccurate data. 

This will hopefully fix #1005. This test fails when adding a component to the blueprint due to an issue concatenating. The handleAddComponent function concats twice with the blueprint components and blueprint packages. Conditionally rendering the input list should fix this issue.

### CODE REVIEW

File: pages/blueprintEdit/index.js [hunk 1]
```diff
@@ -644,13 +644,15 @@ class EditBlueprintPage extends React.Component {
...
                 </div>
               )}
-            <ComponentInputs
-              label={formatMessage(messages.listTitleAvailableComps)}
-              components={inputComponents[inputs.selectedInputPage]}
-              handleComponentDetails={this.handleComponentDetails}
-              handleAddComponent={this.handleAddComponent}
-              handleRemoveComponent={this.handleRemoveComponent}
-            />
+            {(blueprint.components !== undefined && blueprint.packages !== undefined) &&
```
Comment (jgiardino) [inline pages/blueprintEdit/index.js:647]: I'm wondering if this condition should be moved [higher](https://github.com/osbuild/cockpit-composer/pull/1018/files#diff-268ff6cc6477c8bc85a815bc0b236684R574) and combined with the following condition:
`{(inputComponents !== undefined && (`

Because including this condition here results in the following result:
image

But if we move it higher, I think we'd continue to see the loading state while we wait for the blueprint to finish loading, which seems like a better behavior:
image

BTW, I can't actually test this condition, because the blueprint always loads faster than the inputs, and I'm not sure how to reproduce the reverse.

Comment (jkozol) [reply pages/blueprintEdit/index.js]: Thanks for the suggestion! I moved the conditional up. I can also not reproduce it. This is just my best attempt to fix #1005 without being able to replicate it.

**Comment by henrywang** [comment]
@larskarlitski, @gicmo: There're two selinux error on osbuild:
```
audit: type=1400 audit(1593198435.846:2947): avc:  denied  { nnp_transition nosuid_transition } for  pid=36979 comm="semodule" scontext=system_u:system_r:osbuild_t:s0 tcontext=system_u:system_r:setfiles_mac_t:s0 tclass=process2 permissive=0
audit: type=1401 audit(1593198435.846:2947): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:osbuild_t:s0 newcontext=system_u:system_r:setfiles_mac_t:s0
audit: type=1400 audit(1593198492.978:2948): avc:  denied  { nnp_transition nosuid_transition } for  pid=47083 comm="dracut" scontext=system_u:system_r:osbuild_t:s0 tcontext=system_u:system_r:setfiles_mac_t:s0 tclass=process2 permissive=0
audit: type=1401 audit(1593198492.978:2948): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:osbuild_t:s0 newcontext=system_u:system_r:setfiles_mac_t:s0
```
Is this bug or just ignore them? Thanks!

**Comment by jkozol** [comment]
@henrywang I moved this discussion to #1022. Since this PR passes the travis and rhel-8-3 tests I am going to merge it to master and include it in the next rhel release.
